# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override dg-docassembly microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

tags:
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: false                     # blob storage for dm-store

### EM SERVICES ###
dg-docassembly:
  docassembly-api:
    image: hmctspublic.azurecr.io/dg/docassembly:latest
    environment:
      DM_STORE_APP_URL: http://dg-docassembly-dm-store
      IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
      S2S_BASE_URI: http://dg-docassembly-rpe-s2s
      DOCMOSIS_TEMPLATES_ENDPOINT: https://docmosis-development.platform.hmcts.net
      DOCMOSIS_ENDPOINT: https://docmosis-development.platform.hmcts.net/rs/render

###### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: dg-docassembly-rpe-s2s
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest

dm-store:
  java:
    releaseNameOverride: dg-docassembly-dm-store
    image: hmctspublic.azurecr.io/dm/store:latest
    secrets:
      STORAGE_ACCOUNT_NAME:
        disabled: true
      STORAGE_ACCOUNT_KEY:
        disabled: true
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
        disabled: true
    keyVaults:
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-dg-docassembly-ci-test-postgresql:5432/evidence'
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      ENABLE_AZURE_STORAGE_CONTAINER: 'false'
      POSTGRES_STORAGE_ENABLED: 'true'
      STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=AAAAAAAAAAAAAAAA;AccountKey=AAAAAAAAAAAAAAAA;EndpointSuffix=core.windows.net'
      IDAM_USER_BASE_URI: https://idam-api.aat.platform.hmcts.net
      IDAM_S2S_BASE_URI: http://dg-docassembly-rpe-s2s

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  persistence:
    enabled: false