# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override dg-docassembly microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

#global:
#  environment: demo
#  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
#  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

tags:
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: false                     # blob storage for dm-store

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE USER evidence WITH PASSWORD 'evidence';
      CREATE DATABASE evidence WITH OWNER = evidence ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  nameOverride: postgres-db
  persistence:
    enabled: false

### EM SERVICES ###
dg-docassembly:
  docassembly-api:
    image: hmctspublic.azurecr.io/dg/docassembly:latest
    environment:
      DM_STORE_APP_URL: http://chart-dg-docassembly-dm-store
      IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
      S2S_BASE_URI: http://chart-dg-docassembly-rpe-s2s
      DOCMOSIS_TEMPLATES_ENDPOINT: https://docmosis-development.platform.hmcts.net
      DOCMOSIS_ENDPOINT: https://docmosis-development.platform.hmcts.net/rs/render

###### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: chart-dg-docassembly-rpe-s2s
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest

dm-store:
  java:
    releaseNameOverride: chart-dg-docassembly-dm-store
    image: hmctspublic.azurecr.io/dm/store:latest
    keyVaults:
    environment:
      IDAM_USER_BASE_URI: https://idam-api.aat.platform.hmcts.net
      IDAM_S2S_BASE_URI: http://chart-dg-docassembly-rpe-s2s
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-dg-docassembly-postgres-db:5432/evidence'
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      CCD_DM_STORE_STORAGE_ACC_PRIMARY_CONN_STRING: 'dm-store-storage-account-primary-connection-string'
      CCD_DM_STORE_STORAGE_ACC_SECONDARY_CONN_STRING: 'dm-store-storage-account-secondary-connection-string'

